name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
version: 0.7.4+1
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  just_audio_platform_interface: ^3.0.0
  just_audio_web: ^0.3.1
  audio_session:
    git:
      url: https://github.com/brancedev/audio_session.git
  rxdart: ^0.25.0
  path: ^1.8.0
  path_provider: ^2.0.0
  async: ^2.5.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
